---
title: "Data 621 Homework 1"
author: "Critical Thinking Group 3: Vyannna Hill, Jose Rodriguez, and Christian Uriostegui"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include=FALSE}
library(tidyverse)
library(ggpubr)

training_set<-read_csv("https://raw.githubusercontent.com/Vy4thewin/criticalthinking3/main/moneyball-training-data.csv")
test_set<-read_csv("https://raw.githubusercontent.com/Vy4thewin/criticalthinking3/main/moneyball-evaluation-data.csv")
```

### Exploring the MoneyBall game statistics from 1871 to 2006 |DATA EXPLORATION 


```{r include=FALSE}
#Let's review our training set and if the training set needs updates before its process
summary(training_set)

#See the number of NAs per columns. Noticed Batters hit per pitch has the highest 
colSums(is.na(training_set))

#Visually checking for a positive linear trend with a singular predictor value
g<-ggplot(training_set,aes(x=TEAM_BATTING_BB,y=TARGET_WINS))+geom_point()+theme_classic()
# ploting the wins vs home runs
g1<-ggplot(training_set,aes(x=TEAM_BATTING_HR,y=TARGET_WINS))+geom_point()+theme_classic()

#Viewing multiple graphs with a selected predictor variable and its response (wins)
ggarrange(g,g1,ncol = 2,nrow = 1)

```


### Preparing the game stats data set for regressions |DATA PREPARATION


```{r include=FALSE}
#Noticed there are entries with NAs values that cannot be replaced with a formula. These entries will be removed from the training_set to prevent a inaccurate model
train.clean<-na.omit(training_set)

#remove the index column as it does not a have effect in the data
train.clean<-train.clean%>%select(-c(INDEX))

#optional, remove hbp column and remove NAs, Only if score is <significant. Data set

#optional, scale the training set so its easier for the system to process the data in the regression model
train.clean<-scale(train.clean)

#

```

### Selecting the predictor values for our model| BUILD MODELS 


### The final model's predicted highest number of wins| SELECT MODELs

```{r}

#predict (winning lm, new data= test data)
#predicts, prediction will show a table of predicted wins. max(predict)-> highest predicted wins of moneyball

#CI on the predictions. 95% confidenece would be nice


#plot of the predicts of LM()

#normality of the winning model [It should pass linearity]




```


### Appendix

```{r}
#All Code will be display here
library(tidyverse)
library(ggpubr)

training_set<-read_csv("https://raw.githubusercontent.com/Vy4thewin/criticalthinking3/main/moneyball-training-data.csv")
test_set<-read_csv("https://raw.githubusercontent.com/Vy4thewin/criticalthinking3/main/moneyball-evaluation-data.csv")


#Let's review our training set and if the training set needs updates before its process
summary(training_set)

#See the number of NAs per columns. Noticed Batters hit per pitch has the highest 
colSums(is.na(training_set))

#Visually checking for a positive linear trend with a singular predictor value
g<-ggplot(training_set,aes(x=TEAM_BATTING_BB,y=TARGET_WINS))+geom_point()+theme_classic()
# ploting the wins vs home runs
g1<-ggplot(training_set,aes(x=TEAM_BATTING_HR,y=TARGET_WINS))+geom_point()+theme_classic()

#Viewing multiple graphs with a selected predictor variable and its response (wins)
ggarrange(g,g1,ncol = 2,nrow = 1)

#Noticed there are entries with NAs values that cannot be replaced with a formula. These entries will be removed from the training_set to prevent a inaccurate model
train.clean<-na.omit(training_set)

#remove the index column as it does not a have effect in the data
train.clean<-train.clean%>%select(-c(INDEX))

#optional, remove hbp column and remove NAs, Only if score is <significant. Data set

#optional, scale the training set so its easier for the system to process the data in the regression model
train.clean<-scale(train.clean)

````



